<a href="https://colab.research.google.com/github/i-m-akash/house-price-prediction/blob/main/house_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
df=pd.read_csv('/content/drive/MyDrive/ML/kc_house_data.csv')
print(df)

               id             date     price  bedrooms  bathrooms  \
0      7129300520  20141013T000000  221900.0         3       1.00
1      6414100192  20141209T000000  538000.0         3       2.25
2      5631500400  20150225T000000  180000.0         2       1.00
3      2487200875  20141209T000000  604000.0         4       3.00
4      1954400510  20150218T000000  510000.0         3       2.00
...           ...              ...       ...       ...        ...
21608   263000018  20140521T000000  360000.0         3       2.50
21609  6600060120  20150223T000000  400000.0         4       2.50
21610  1523300141  20140623T000000  402101.0         2       0.75
21611   291310100  20150116T000000  400000.0         3       2.50
21612  1523300157  20141015T000000  325000.0         2       0.75

       sqft_living  sqft_lot  floors  waterfront  view  ...  grade  \
0             1180      5650     1.0           0     0  ...      7
1             2570      7242     2.0           0     0  ...      7
2              770     10000     1.0           0     0  ...      6
3             1960      5000     1.0           0     0  ...      7
4             1680      8080     1.0           0     0  ...      8
...            ...       ...     ...         ...   ...  ...    ...
21608         1530      1131     3.0           0     0  ...      8
21609         2310      5813     2.0           0     0  ...      8
21610         1020      1350     2.0           0     0  ...      7
21611         1600      2388     2.0           0     0  ...      8
21612         1020      1076     2.0           0     0  ...      7

       sqft_above  sqft_basement  yr_built  yr_renovated  zipcode      lat  \
0            1180              0      1955             0    98178  47.5112
1            2170            400      1951          1991    98125  47.7210
2             770              0      1933             0    98028  47.7379
3            1050            910      1965             0    98136  47.5208
4            1680              0      1987             0    98074  47.6168
...           ...            ...       ...           ...      ...      ...
21608        1530              0      2009             0    98103  47.6993
21609        2310              0      2014             0    98146  47.5107
21610        1020              0      2009             0    98144  47.5944
21611        1600              0      2004             0    98027  47.5345
21612        1020              0      2008             0    98144  47.5941

          long  sqft_living15  sqft_lot15
0     -122.257           1340        5650
1     -122.319           1690        7639
2     -122.233           2720        8062
3     -122.393           1360        5000
4     -122.045           1800        7503
...        ...            ...         ...
21608 -122.346           1530        1509
21609 -122.362           1830        7200
21610 -122.299           1020        2007
21611 -122.069           1410        1287
21612 -122.299           1020        1357

[21613 rows x 21 columns]

In [4]:
df=df.drop(columns='date',axis=1)
df

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,263000018,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [5]:
df.isnull().sum()

id               0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [6]:
X=df.drop(columns='price',axis=1)
Y=df['price']

In [7]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
#Split the dataset
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, random_state=2)

In [8]:
X_train

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
15166,3304700130,4,4.00,3860,67953,2.0,0,2,4,12,3860,0,1927,0,98177,47.7469,-122.378,4410,128066
13416,1115100119,4,2.00,1920,7803,1.0,0,0,3,7,1080,840,1962,0,98155,47.7580,-122.325,1940,8147
206,9526600140,3,2.50,2440,4587,2.0,0,0,3,8,2440,0,2010,0,98052,47.7073,-122.114,2750,4587
4286,9264921140,3,2.75,1910,15508,1.0,0,0,3,8,1210,700,1984,0,98023,47.3128,-122.345,2450,7989
18065,3826500730,4,2.50,2130,9100,1.0,0,0,3,8,1290,840,1978,0,98030,47.3815,-122.169,1770,7700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099,7227500830,2,1.00,720,4222,1.0,0,0,4,5,720,0,1942,0,98056,47.4965,-122.186,860,4785
18898,984220330,4,2.50,1820,9161,1.0,0,0,4,7,1220,600,1975,0,98058,47.4333,-122.168,1860,7650
11798,3629920990,4,3.25,3440,7661,2.0,0,0,3,11,3440,0,2006,0,98029,47.5429,-121.995,3580,6478
6637,3126049439,2,1.50,870,747,2.0,0,0,3,8,800,70,2004,0,98103,47.6967,-122.342,1710,1280
2575,3629970240,3,2.50,2820,5001,2.0,0,0,3,9,2820,0,2004,0,98029,47.5533,-121.992,2660,5001

In [9]:
Y_train

15166    1755000.0
13416     360000.0
206       677900.0
4286      300000.0
18065     220000.0
           ...
1099      151000.0
18898     325000.0
11798     905000.0
6637      313000.0
2575      690000.0
Name: price, Length: 17290, dtype: float64

In [10]:
X_test

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
6638,3491300052,4,2.25,2410,4250,1.5,0,0,5,7,1460,950,1929,0,98117,47.6849,-122.376,1360,5074
7366,8917100020,3,1.50,2170,16600,1.0,1,2,3,10,1130,1040,1979,0,98052,47.6307,-122.088,3130,13875
3158,5100401429,2,1.00,1450,6380,1.0,0,0,3,7,1450,0,1967,0,98115,47.6924,-122.321,1240,6380
9117,1454600156,5,3.25,4500,9648,2.0,0,4,4,8,3000,1500,1968,0,98125,47.7262,-122.282,2780,21132
3392,1917300025,2,1.00,860,6000,1.0,0,0,3,6,860,0,1945,0,98022,47.2109,-121.985,1300,6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8494,7305300090,4,1.75,1530,8152,1.0,0,0,5,6,910,620,1948,0,98155,47.7557,-122.328,1310,8152
5359,2310030500,3,1.75,1580,9187,1.0,0,0,3,8,1180,400,1993,0,98038,47.3538,-122.047,1620,6397
5242,1515910290,4,2.50,2650,9451,2.0,0,0,4,8,2650,0,1993,0,98042,47.3693,-122.129,2510,8850
13777,7625703065,2,1.00,820,6250,1.0,0,0,4,5,820,0,1922,0,98136,47.5479,-122.384,1300,6250
1080,7888400560,4,2.75,1810,8677,1.5,0,0,3,7,1810,0,1962,0,98198,47.3668,-122.310,1740,8677

In [11]:
Y_test

6638      735000.0
7366     1150000.0
3158      350500.0
9117      860000.0
3392      122000.0
           ...
8494      338000.0
5359      263000.0
5242      397450.0
13777     375000.0
1080      208000.0
Name: price, Length: 4323, dtype: float64

In [12]:

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

# get numeric data
num_v = df.select_dtypes(exclude=['object'])

# update the cols with their normalized values
df[num_v.columns] = sc.fit_transform(num_v)

# convert string variable to One Hot Encoding
#Handling categorical features
df1 = pd.get_dummies(df)

df1.head(10)

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,0.886146,-0.866717,-0.398737,-1.447464,-0.979835,-0.228321,-0.915427,-0.087173,-0.305759,-0.629187,-0.558836,-0.734708,-0.658681,-0.544898,-0.210128,1.870152,-0.352572,-0.306079,-0.943355,-0.260715
1,0.637511,-0.005688,-0.398737,0.175607,0.533634,-0.189885,0.936506,-0.087173,-0.305759,-0.629187,-0.558836,0.460841,0.245141,-0.681079,4.746678,0.879568,1.161568,-0.746341,-0.432686,-0.187868
2,0.365444,-0.980849,-1.473959,-1.447464,-1.426254,-0.123298,-0.915427,-0.087173,-0.305759,-0.629187,-1.409587,-1.229834,-0.658681,-1.293892,-0.210128,-0.933388,1.283537,-0.135655,1.070140,-0.172375
3,-0.727656,0.174090,0.676485,1.149449,-0.130550,-0.244014,-0.915427,-0.087173,-0.305759,2.444294,-0.558836,-0.891699,1.397515,-0.204446,-0.210128,1.085160,-0.283288,-1.271816,-0.914174,-0.284522
4,-0.912881,-0.081958,-0.398737,-0.149007,-0.435422,-0.169653,-0.915427,-0.087173,-0.305759,-0.629187,0.291916,-0.130895,-0.658681,0.544548,-0.210128,-0.073636,0.409550,1.199335,-0.272190,-0.192849
5,0.923779,1.865641,0.676485,3.097133,3.636791,2.096185,-0.915427,-0.087173,-0.305759,-0.629187,2.844170,2.537955,2.798440,1.021181,-0.210128,-0.466132,0.693181,1.483375,4.046611,3.265566
6,-1.132940,-0.769746,-0.398737,0.175607,-0.397313,-0.200098,0.936506,-0.087173,-0.305759,-0.629187,-0.558836,-0.088628,-0.658681,0.816910,-0.210128,-1.400645,-1.806810,-0.803149,0.366876,-0.217900
7,-0.894247,-0.676180,-0.398737,-0.798235,-1.110494,-0.130276,-0.915427,-0.087173,-0.305759,-0.629187,-0.558836,-0.879623,-0.658681,-0.272536,-0.210128,2.243957,-1.086547,-0.717937,-0.491048,-0.111980
8,-0.752895,-0.846016,-0.398737,-1.447464,-0.326539,-0.184381,-0.915427,-0.087173,-0.305759,-0.629187,-0.558836,-0.891699,0.990795,-0.374672,-0.210128,1.272063,-0.344633,-0.874160,-0.301371,-0.170507
9,-0.273527,-0.591330,-0.398737,0.500221,-0.206768,-0.206351,0.936506,-0.087173,-0.305759,-0.629187,-0.558836,0.122706,-0.658681,1.089271,-0.210128,-0.746486,-1.383168,1.298749,0.588652,-0.190395

In [13]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [14]:
model.fit(X_train,Y_train)

LinearRegression()

In [15]:
X_train_prediction=model.predict(X_train)
training_data_accuracy=model.score(X_train,Y_train)
training_data_accuracy

0.6955783384235752

In [16]:
X_test_prediction=model.predict(X_test)
testing_data_accuracy=model.score(X_test,Y_test)
testing_data_accuracy

0.7157355068831226

In [17]:
from sklearn.metrics import mean_squared_error
rmse_test=mean_squared_error(X_test_prediction,Y_test)**0.5
print(rmse_test)

199212.58481315887

In [18]:
dataframe1={
    'id':[7891456458,6414100192],
    'bedrooms':[6,3],
    'bathrooms':[6,2.25],
    'sqft_living':[5340,2570],
    'sqft_lot':[12500,7242],
    'floors':[3,2],
    'waterfront':[6,0],
    'view':[2,0],
    'condition':[6,3],
    'grade':[3,7],
    'sqft_above':[870,2170],
    'sqft_basement':[700,400],
    'yr_built':[1003,1451],
    'yr_renovated':[2253,1991],
    'zipcode':[98705,98125],
    'lat':[47.6007,47.7210],
    'long':[-163.3445,-122.319],
    'sqft_living15':[1250,1690],
    'sqft_lot15':[6330,7639]
}

dataf=pd.DataFrame(dataframe1)
dataf

,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7891456458,6,6.00,5340,12500,3,6,2,6,3,870,700,1003,2253,98705,47.6007,-163.3445,1250,6330
1,6414100192,3,2.25,2570,7242,2,0,0,3,7,2170,400,1451,1991,98125,47.7210,-122.3190,1690,7639

In [19]:
predict_price=model.predict(dataf)
print(predict_price)

[15101867.93442671  2044078.82071425]